name: Markdown Meta
description: Read front-matter from Markdown files
runs:
  using: docker
  image: Dockerfile
branding:
  icon: edit-2
  color: orange
inputs:
  file:
    description: The file to read
    required: true
